* Error message strings
* Public domain version 2.0

NOPRO HEX 8D
 ASC "Warp Six BBS requires ProDOS.",8D8D8700

NOBAS HEX 8D
 ASC "Warp Six BBS requires BASIC.System.",8D8D8700

UNKNOWN HEX 8D
 ASC "Sorry, non-Apple or unknown computer.",8D8D8700

OLDCPU HEX 8D
 ASC "Apple IIe Enhanced or IIgs required.",8D8D8700

A3 HEX 8D
 ASC "You need a IIe or IIGS to run Warp Six.",8D8D
 ASC "(You didn't really expect this to work on",8D
 ASC "an Apple III, did you?)",8D8D8700

NO80COL HEX 8D
 ASC "Could not find an 80 column card.",8D8D
 ASC "Please install an extended or regular 80",8D
 ASC "column card for Warp Six BBS compatibility.",8D8D8700

ORGIIE HEX 8D
 ASC "This Apple IIe is not enhanced.",8D8D
 ASC "Your IIe needs to be enhanced to support",8D
 ASC "Warp Six BBS. To upgrade, obtain the",8D
 ASC "the IIe Enhancement Kit, part #A2M2052.",8D8D8700

APIIC HEX 8D
 ASC "This version of Warp Six BBS does not",8D
 ASC "support the Apple IIc or IIc Plus.",8D8D8700

NOVBL HEX 8D
 ASC "Fatal error: Cannot detect vertical blanking.",8D8D
 ASC "Apple IIe Enhanced or IIgs required.",8D8D8700

GSROM0 HEX 8D
 ASC "This IIGS has the original version ROM.",8D8D
 ASC "Warp Six BBS will still run on your",8D
 ASC "system, but you may want the free",8D
 ASC "upgrade to ROM 01 from your dealer.",8D8D8700

NEWCPU HEX 8D
 ASC "This CPU not supported; unknown.",8D8D8700

LCCARD HEX 8D
 ASC "Warp Six can't run on the IIe Card.",8D8D
 ASC "Apple IIe Enhanced or IIgs required.",8D8D8700

NEEDGS HEX 8D
 ASC "This modem driver requires an Apple IIgs.",8D8D
 ASC "For the IIe, use the SSC modem driver.",8D8D8700

YOURCARD HEX 8D
 ASC "Warp Six BBS requires slot 2 to be set to",8D
 ASC "Modem Port, in your Control Panel. Please set",8D
 ASC "it via your Control Panel and restart.",8D8D8700

APTALK HEX 8D
 ASC "Warp Six BBS is not compatible with "
 ASC "AppleTalk. Please disable it and restart.",8D8D8700

FATAL HEX 8D
 ASC "Fatal error initializing modem port.",8D8D
 ASC "Please check your Control Panel "
 ASC "settings and restart.",8D8D8700

NORAM HEX 8D
 ASC "Warp Six BBS cannot be loaded because",8D
 ASC "something has already been loaded into",8D
 ASC "the memory area the modem driver needs.",8D8D
 ASC "To cure the problem, please restart",8D
 ASC "BASIC.System or remove the offender.",8D8D00
